CREATE type SurveyEventType as ENUM ('displayed', 'responded', 'completed');

CREATE TABLE events (
  id bigint generated by default as identity primary key,

  survey_id EntityId not null,
  instance_id text not null,
  question_id EntityId null,
  type SurveyEventType not null,

  user_token text not null,

  created timestamp with time zone default timezone('utc'::text, now()) not null,
  updated timestamp with time zone default timezone('utc'::text, now()) not null,

  CONSTRAINT fkSurvey
      FOREIGN KEY(survey_id) 
      REFERENCES surveys(id),

	CONSTRAINT fkQuestion
      FOREIGN KEY(question_id) 
      REFERENCES questions(id)
);