DROP TABLE IF EXISTS surveys;

CREATE TABLE IF NOT EXISTS surveys (
  surveyId SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM ('fixed', 'modal') NOT NULL,
  display ENUM ('always', 'user', 'session') NOT NULL,
  status ENUM ('active', 'inactive') NOT NULL,
  triggerConfig JSON NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  updated TIMESTAMP NOT NULL DEFAULT NOW()
);



CREATE type SurveyType as ENUM ('fixed', 'modal');
CREATE type SurveyDisplay as ENUM ('always', 'user', 'session');
CREATE type SurveyStatus as ENUM ('active', 'inactive');


CREATE TABLE surveys (
  id bigint generated by default as identity primary key,
  containerId bigint not null,
  name VARCHAR(255) NOT NULL,
  type SurveyType NOT NULL,
  display SurveyDisplay NOT NULL,
  status SurveyStatus NOT NULL,
  triggerConfig JSON NOT NULL,
  created timestamp with time zone default timezone('utc'::text, now()) not null,
  updated timestamp with time zone default timezone('utc'::text, now()) not null,

  CONSTRAINT fkContainer
      FOREIGN KEY(containerId) 
      REFERENCES containers(id)
);